/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package email;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JFileChooser;

/**
 *
 * @author danii
 */
public class SendEmailGUI extends javax.swing.JFrame {

    /**
     * Creates new form SendEmailGUI
     */
    public SendEmailGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        Attach = new javax.swing.JButton();
        To = new javax.swing.JTextField();
        Subject = new javax.swing.JTextField();
        MessageScroll = new javax.swing.JScrollPane();
        Message = new javax.swing.JTextArea();
        Close = new javax.swing.JLabel();
        Send = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(625, 450));
        setMinimumSize(new java.awt.Dimension(625, 450));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Attach.setText("Attach");
        Attach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AttachMouseReleased(evt);
            }
        });
        Attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttachActionPerformed(evt);
            }
        });
        getContentPane().add(Attach, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        To.setBorder(null);
        To.setOpaque(false);
        To.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToActionPerformed(evt);
            }
        });
        getContentPane().add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 520, 70));

        Subject.setBorder(null);
        Subject.setOpaque(false);
        getContentPane().add(Subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 520, 80));

        MessageScroll.setBorder(null);

        Message.setColumns(20);
        Message.setRows(5);
        Message.setBorder(null);
        Message.setOpaque(false);
        MessageScroll.setViewportView(Message);

        getContentPane().add(MessageScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 510, 160));

        Close.setText("X");
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CloseMouseReleased(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 10, 30));

        Send.setText("Send");
        Send.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Send.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SendMouseReleased(evt);
            }
        });
        getContentPane().add(Send, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 424, 60, 20));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email/images/SendEmailImage.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 625, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseReleased
        super.dispose();
    }//GEN-LAST:event_CloseMouseReleased

    private void SendMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendMouseReleased
        try 
        {
            SendEmail SE = new SendEmail();
            SE.SendEmail(To.getText(), Subject.getText(), Message.getText());
            super.dispose();
        } 
        catch (MessagingException ex) 
        {
            Logger.getLogger(SendEmailGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SendMouseReleased

    private void ToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToActionPerformed

    private void AttachMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttachMouseReleased
        int returnVal = fileChooser.showOpenDialog(this);
        String filePath;
        String fileName;
        if (returnVal == JFileChooser.APPROVE_OPTION) 
        {
            File file = fileChooser.getSelectedFile();
            filePath = file.getAbsolutePath();
            //get file path and name
            SendEmail SE = new SendEmail();
            SE.addFilePath(filePath);
            fileName = file.getName();
            SE.addFileName(fileName);
        } 
        else 
        {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_AttachMouseReleased

    private void AttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AttachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendEmailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendEmailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendEmailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendEmailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SendEmailGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Attach;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Close;
    private javax.swing.JTextArea Message;
    private javax.swing.JScrollPane MessageScroll;
    private javax.swing.JLabel Send;
    private javax.swing.JTextField Subject;
    private javax.swing.JTextField To;
    private javax.swing.JFileChooser fileChooser;
    // End of variables declaration//GEN-END:variables
}
